server:
  port: 8099
spring.jackson.mapper.sort_properties_alphabetically: true
spring.jackson.property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

kafka:
  consumer:
    zookeeper:
      connect: 138.138.81.191:2181,138.138.81.192:2181,138.138.81.193:2181
      session.timeout.ms: 4000
      sync.time.ms: 200
    group:
      id: zdtest
    auto:
      commit.interval.ms: 1000
      offset.reset: smallest
    serializer.class: kafka.serializer.StringEncoder
    default:
      topic: hulu
  producer:
    broker:
      list: 138.138.81.195:9092,138.138.81.196:9092,138.138.81.197:9092
    serializer:
      class: kafka.serializer.StringEncoder
    key:
      serializer:
        class: kafka.serializer.StringEncoder
    request:
      required:
        acks: 1
    partitioner:
      class: kafka.producer.DefaultPartitioner
